# Generated by Django 5.0.6 on 2024-06-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contato", "0002_contato_show"),
    ]

    operations = [
        migrations.AddField(
            model_name="contato",
            name="img",
            field=models.ImageField(blank=True, upload_to="images/%Y/%m"),
        ),
    ]
