# Generated by Django 5.0.6 on 2024-06-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contato", "0004_alter_contato_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contato",
            name="img",
            field=models.ImageField(default="imgs/1.png", upload_to="images/%Y/%m"),
        ),
    ]
